name: Hexo Auto-Deploy
on: 
  push:
    
  schedule:
    - cron: "0 8 * * *"


jobs:
  build:
    name: Github repo Auto-Sync to Gitee, by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: 0. config 
      run: |        
        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: 1. scoop 
      run: |
        cd /home/runner/work/
        git clone https://github.com/ScoopInstaller/Scoop.git
        cd Scoop/
        gitee_repo='https://shenbo1989:${{secrets.GITEE_PASSWORD}}@gitee.com/shenbo1989/ScoopInstaller_Scoop.git'
        git remote add gitee ${gitee_repo}
        git push --all --force gitee

    - name: 2. buckets 
      run: |
        cd /home/runner/work/
        git clone https://github.com/ScoopInstaller/Main.git
        cd Main/
        gitee_repo='https://shenbo1989:${{secrets.GITEE_PASSWORD}}@gitee.com/shenbo1989/ScoopInstaller_Main.git'
        git remote add gitee ${gitee_repo}
        git push --all --force gitee
        
        # ---------------------
